name: Publish RSS feed

on:
  schedule:
    - cron: '29 01 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run main.py
        run: |
          mkdir -p assets/
          python main.py $id
        env:
          id: 9412
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'assets/'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    needs: main
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Pages
        id: deployment
        uses: actions/deploy-pages@v4
